version: '2'
services:
    app:
      build:
          context: deploy
          dockerfile: app.docker
      environment:
        - "DB_HOST=database"
        - "DB_DATABASE=db"
        - "DB_USERNAME=root"
        - "DB_PASSWORD=secret"
      volumes:
          - ./:/var/www/html
      ports:
          - "80:80"
      links:
          - database
    database:
      image: mysql:5.7
      environment:
        - "MYSQL_ROOT_HOST=%"
        - "MYSQL_ROOT_USERNAME=root"
        - "MYSQL_ROOT_PASSWORD=secret"
        - "MYSQL_DATABASE=db"
      ports:
          - "33061:3306"
